### ISSUE TITLE
vhdi-tools for CentOS

### ISSUE THREAD

**Issue by penetal** [ronivay/XenOrchestraInstallerUpdater#10]
Moving the discussion to a new issue would probably make sense.

_Originally posted by @penetal in https://github.com/ronivay/XenOrchestraInstallerUpdater/pull/9#issuecomment-427829951_

Do you know if there is any way to get vhdi-tools on CentOS? Would love to have file level restore without having to get a single VM that is different than the rest of our environment.

**Comment by ronivay** [comment]
I managed to get the file level restore from delta backups to work when the backup VHD from the VM doesn't contain LVM. Not sure yet if this is a pure CentOS issue or CentOS/XO combined. So far it seems that this is CentOS issue but will investigate more before final verdict.

**Comment by ronivay** [comment]
It seems that this indeed is CentOS related and the way it handles things somehow differently. Unfortunately I'm unable to pinpoint the actual reason why this doesn't work, so I'm going to implement this as is, so that CentOS installation is able to do file level restore from disks which don't contain LVM. Ubuntu/Debian installations handle also LVM without issues.

**Comment by ronivay** [comment]
vhdi-tools are now included to CentOS installation in commit: https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/6351dbf933065e88fb653a5b08a7dd33bef4be40

Unfortunately for restores from LVM, all i can recommend now is to use Debian/Ubuntu installation
