### ISSUE TITLE
Add support for provisioning a XO proxy

### ISSUE THREAD

**Issue by hoerup** [ronivay/XenOrchestraInstallerUpdater#104]
According to 
https://xcp-ng.org/forum/topic/3951/is-xo-proxy-available-in-community-version 

It should be possible to setup a community version of XO proxy although official howto remains to be seen.

Would be nice if this project could be used to setup a XO proxy instance as well

**Comment by ronivay** [comment]
Hi,

Thanks for suggestion. I've been meaning to take a look into this. It seems fairly simple with a quick glance but the there are some question marks like how should one register the proxy to from sources built xen orchestra. It can be done with partial config restore with just the proxy details but would be nice to have an option in the UI to just register proxy (without deploying the appliance that XOA does). But since there isn't one the config restore might be the easiest way to go. Let's see, i'll poke around a bit more :)

**Comment by ronivay** [comment]
Some progress here. I managed to implement the proxy installation into the script with it's own menu options for install/update procedures. Proxy can be registered to Xen Orchestra with one line of json and config import which the script will generate and output in the end of installation. 

Only issue is that proxy process really seems to want to talk to xoa-updater which checks for example the license status for proxy. That obviously isn't there as it's part of the official appliance deployment. This seems to prevent backup jobs from starting even though for example remote mounting works without issues. I can prevent this by simply commenting out the license check piece of code from proxy backup and backup/restore functions seem to work just fine. I'm just not a huge fan of touching the source code and would love to simply have a config option, env var or something to let proxy know that it's from sources and shouldn't do any license/upgrade checks.

**Comment by ronivay** [comment]
First version available in feature branch. Will do some more testing with it before merging, but feel free to give it a spin.

https://github.com/ronivay/XenOrchestraInstallerUpdater/tree/feat/xo-proxy

**Comment by ronivay** [comment]
Alrighty, after some polishing and testing with deb/rpm variants. This feature is now merged to master.

Testing and feedback is appreciated if i managed to miss something obvious. Will close this for now.
