### ISSUE TITLE
XOSAN and Hub not available?

### ISSUE THREAD

**Issue by brandenk514** [ronivay/XenOrchestraInstallerUpdater#125]
**OS Version**: Debain 11
**Node.js version**: node -v -> v16.15.1
**Yarn version**: yarn -v -> 1.22.19

**Server specs**
4 vCPUs and 4GB of RAN

**Issue**
Is XOSAN and Hub supposed to be missing? When I try to access it, I get a message that "Hub is available in XOA". I read through the readme and past issues, but I didn't see anything about it. Your help is much appreciated! Thank you!

**Installation logfile**
Attach complete log as a file. 
[xo-install-log-202206041724.log](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/8839153/xo-install-log-202206041724.log)

**Comment by vmpr** [comment]
Yes xosan and hub are not available in xen Orchestra from sources. You need to use the pay version

**Comment by MasterMNB** [comment]
The Hub can be used in the free XOA (https://xen-orchestra.com/#!/xoa) but not with XO from the sources.
There you can also test with a 50GiB limit XOSANv1 https://xen-orchestra.com/docs/xosan.html#try-it 
XOSANv2 is in Beta https://xen-orchestra.com/docs/xosanv2.html
XOSTOR also still in development but you can test it https://xcp-ng.org/forum/topic/5361/xostor-hyperconvergence-preview

**Comment by ronivay** [comment]
Hi,

Good answers here already. So yes, they are supposed to be missing from XO from sources installations. Even though majority of features are available in XO from sources installations. There are certain things that aren't natively built into XenServer/XCP-ng (XOSAN/XOSTOR, hub, host telemetry to name a few) and can only be easily installed/used through XOA. This is part of the added value you get from the appliance and subscription.

In theory, since it's open source, one could implement something similar to their XO from sources installation with some modifications. That's out of scope what this repository offers, which is an automated installation of documented XO from sources installation procedure with some additions to make life easier. 

I'll close this for now. If there's any further questions about the topic, feel free to continue commenting.
