### ISSUE TITLE
Service does not start after installation through the script

### ISSUE THREAD

**Issue by michal-rybinski** [ronivay/XenOrchestraInstallerUpdater#156]
**OS Version**: Rocky 8, Ubuntu 22.04 (both LXC on Poxmox if that matters)
**Node.js version**: node -v = v16.18.1
**Yarn version**: yarn -v = 1.22.19

**Server specs**
2 vCPUs , 3GB RAM

**Issue**
Installed fine, no problems or errors, but when script tries to start the service it bails out with error pointing at wrong "export" from node uuid library. The same process and the same error on both OS platforms.

**Installation logfile**
Attach complete log as a file. 
[xo-install.log-202211281934.log](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/10107071/xo-install.log-202211281934.log)

**Comment by ronivay** [comment]
Seems to be due to this commit: https://github.com/vatesfr/xen-orchestra/commit/72c69d791a7808fc68a85cb26a12ca0e633fbfcf

My tests are failing as well. Need to run couple tests before reporting that issue to XO repo. Will look into this asap. For now you can set the BRANCH in xo-install.cfg to `d6192a4a7a34921370d048da2f629704da784f7d` and it run update.

**Comment by ronivay** [comment]
Should be fixed now. Can you confirm

**Comment by michal-rybinski** [comment]
Hi, thanks for the updates and quick actioning. I will be able to test it when I get back from work today in the evening UTC time, will provide the result then.

**Comment by ryans1991** [comment]
I was having a similar issue last night where XO Server failed to start after install but it is working for me now.

**Comment by michal-rybinski** [comment]
Yay, can confirm the current version works as expected :) 
Thanks!
[](url)
