### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by chevybeef** [ronivay/XenOrchestraInstallerUpdater#16]
Running installation...done

No plugins to install

Fixing binary path in systemd service configuration file

Adding WorkingDirectory parameter to systemd service configuration file
Fixing relative path to xo-web installation in xo-server configuration file
Activating modified configuration file

Symlinking fresh xo-server install/update to /etc/xo/xo-server
Symlinking fresh xo-web install/update to /etc/xo/xo-web

Replacing systemd service configuration file
Reloading systemd configuration

Starting xo-server...
waiting for port to be open
waiting for port to be open
waiting for port to be open
waiting for port to be open
waiting for port to be open
waiting for port to be open
Something went wrong, exiting. Check ./xo-install.log for more details and use rollback feature if needed
Removing /etc/xo/xo-builds/xen-orchestra-201915011059 because of failed installation.
# less xo-install.log
From https://github.com/vatesfr/xen-orchestra
   ea4813679..e9d187669  master                     -> origin/master
 + 53c199ec5...ca0c72b54 enableDisable-multipathing -> origin/enableDisable-multipathing  (forced update)
 + 17043a415...3ba7f75b0 fix-vm-stats               -> origin/fix-vm-stats  (forced update)

**Comment by ronivay** [comment]
Hmm so service isn’t starting properly. Logs about this don’t end up to logfile unfortunately. Did you use the default configuration (port 80)? If this is a fresh installation. Can you check that nothing else isn’t listening to this port (with netstat for example) already?

You can check service logs with journalctl -u xo-server -n 50 for more information. If this refuses to work then check your syslog for more info.

**Comment by chevybeef** [comment]
Indeed, apache2 was running on that port so I've disabled and rebooted but still can't get xo-server running:

Running apt-get update...done

Installing apt-transport-https and ca-certificates packages to support https repos...done

Installing build dependencies, redis server, python, git, libvhdi-utils, lvm2, nfs-common...done

Enabling and starting redis service...done

Enabling and starting rpcbind service...done

Fetching Xen Orchestra source code ...

Already up-to-date.

Creating install directory: /etc/xo/xo-builds/xen-orchestra-201915011139

done
Something went wrong, exiting. Check ./xo-install.log for more details and use rollback feature if needed
Removing /etc/xo/xo-builds/xen-orchestra-201915011139 because of failed installation.
root@debianzm:/home/mark/XenOrchestraInstallerUpdater# cat xo-install.log
./xo-install.sh: line 331: cd: /etc/xo/xo-server: No such file or directory

root@debianzm:/home/mark/XenOrchestraInstallerUpdater# ls /etc/xo/
xo-builds  xo-server  xo-src  xo-web

**Comment by ronivay** [comment]
Hi,

Okay good, progress :) 

It seems to fail because those symlink do exist, but they don't end up anywhere. This happened because the install directory was deleted after those symlinks were created, but they are not cleaned. I'll see if i come up with a solution for this. I just commited a change so that install directory is not deleted in case only service start fails, so identical situation shouldn't happen anymore. This also puts some more information to log file if service start fails.

**Comment by ronivay** [comment]
Hi,

Installation can now deal with situation where symlinks point to directories that don't exist.: https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/f4146c89601fc17c24b8b04f36941ce914d1a4ce

Althought this situation shouldn't really happen anymore because of: https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/abcfd988139083d0587195819cf0dd94d57d8fd2
