### ISSUE TITLE
installation fails on "waiting for port to be open"

### ISSUE THREAD

**Issue by Solarbotics** [ronivay/XenOrchestraInstallerUpdater#191]
**OS**: Debian 12 Bookworm
**Node.js version**: v18.17.0
**Yarn version**: 1.22.19 

**Server specs**
8 VCPUs, 4GB memory

**Issue**
Running the script as found and linked to from [here](https://forums.lawrencesystems.com/t/xcp-ng-linux-and-xoa/15055).
Seems to operate properly until it gets to the stage:
"waiting for port to be open"

I've since added iptables parameters to allow both 80 and 443, and reran the installation to no avail:
`iptables -A INPUT -p tcp --dport 443 -j ACCEPT`

Error log reports it to be a problem with SOAP.

**Thanks** for having a link to a prebuilt Debian 11 build; that gets me on the way, but thought I should report the glitch I'm seeing here.

**Installation logfile**

[xo-install.log-202307191123.log](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/12098982/xo-install.log-202307191123.log)

**Comment by kevnich2** [comment]
Running into same error.  I just reverted to a previous snapshot from before the update and will try again once this error has been resolved.

**Comment by ronivay** [comment]
As was already mentioned. Due to a change in XO repo.

I guess this might've fixed it. Anyone tried yet? https://github.com/vatesfr/xen-orchestra/commit/363d7cf0d0bcc0dc65d56cbf976f9678b5c5eedb

**Comment by zware** [comment]
Can confirm that vatesfr/xen-orchestra@1c23bd5ff is working fine (or at least started up :) )

**Comment by ronivay** [comment]
> Can confirm that vatesfr/xen-orchestra@1c23bd5ff is working fine (or at least started up :) )

Cheers. Considering this fixed :) feel free to comment back if any others still have issues and i'll reopen.

**Comment by goofy7264** [comment]
I know it's a month later and I'm happy to open a new issue, but I am running into the same "waiting for port to open" issue.  
What is the best approach to provide the details you need to trouble shoot.  Here is my install log
`+ command -v git
/usr/bin/git
+ cd . && git config --get remote.origin.url
https://github.com/ronivay/XenOrchestraInstallerUpdater.git
+ cd . && git status --porcelain
+ cd . && git fetch
+ cd . && git rev-parse --short HEAD
dd2ea64
+ cd . && git rev-parse --short FETCH_HEAD
dd2ea64
+ cd . && git diff --name-only @{upstream}| grep xo-install.sh
Running script version dd2ea64 with config:

PORT="80"
INSTALLDIR="/opt/xo"
SELFUPGRADE=true
CONFIGUPDATE=true
REPOSITORY="https://github.com/vatesfr/xen-orchestra"
BRANCH="master"
PLUGINS="all"
AUTOUPDATE="true"
OS_CHECK="true"
ARCH_CHECK="true"
PRESERVE="3"

+ id -u
0
+ uname -m
x86_64
+ command -v xe
+ grep ^VERSION_ID /etc/os-release | cut -d'=' -f2 | grep -Eo '[0-9]{1,2}' | head -1
22
+ grep ^NAME /etc/os-release | cut -d'=' -f2 | sed 's/"//g' | awk '{print $1}'
Ubuntu
+ grep ^GRUB_DISTRIBUTOR /etc/default/grub | grep 'Xen Orchestra'
+ command -v yum
+ command -v apt-get
/usr/bin/apt-get
+ command -v systemctl
/usr/bin/systemctl
+ df -P -k '/opt' | tail -1 | awk '{print $4}'
13901444
+ grep MemTotal /proc/meminfo | awk '{print $2}'
8102520
+ pgrep -f xo-server
+ apt-get install -y software-properties-common
Reading package lists...
Building dependency tree...
Reading state information...
software-properties-common is already the newest version (0.99.22.7).
software-properties-common set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
+ add-apt-repository -y universe
Hit:1 http://ca.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://ca.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:3 http://ca.archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:4 http://ca.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Fetched 338 kB in 1s (287 kB/s)
Reading package lists...
Adding component(s) 'universe' to all repositories.
+ apt-get update
Hit:1 http://ca.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://ca.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://ca.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://ca.archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists...
+ apt-get install -y build-essential redis-server libpng-dev git libvhdi-utils python3-minimal lvm2 nfs-common cifs-utils curl ntfs-3g dmidecode
Reading package lists...
Building dependency tree...
Reading state information...
build-essential is already the newest version (12.9ubuntu3).
libpng-dev is already the newest version (1.6.37-3build5).
lvm2 is already the newest version (2.03.11-2.1ubuntu4).
libvhdi-utils is already the newest version (20210425-1build1).
redis-server is already the newest version (5:6.0.16-1ubuntu1).
cifs-utils is already the newest version (2:6.14-1ubuntu0.1).
curl is already the newest version (7.81.0-1ubuntu1.13).
curl set to manually installed.
dmidecode is already the newest version (3.3-3ubuntu0.1).
dmidecode set to manually installed.
git is already the newest version (1:2.34.1-1ubuntu1.10).
ntfs-3g is already the newest version (1:2021.8.22-3ubuntu1.2).
ntfs-3g set to manually installed.
python3-minimal is already the newest version (3.10.6-1~22.04).
The following additional packages will be installed:
  libnfsidmap1 rpcbind
Suggested packages:
  watchdog
The following NEW packages will be installed:
  libnfsidmap1 nfs-common rpcbind
0 upgraded, 3 newly installed, 0 to remove and 11 not upgraded.
Need to get 330 kB of archives.
After this operation, 1,284 kB of additional disk space will be used.
Get:1 http://ca.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libnfsidmap1 amd64 1:2.6.1-1ubuntu1.2 [42.9 kB]
Get:2 http://ca.archive.ubuntu.com/ubuntu jammy/main amd64 rpcbind amd64 1.2.6-2build1 [46.6 kB]
Get:3 http://ca.archive.ubuntu.com/ubuntu jammy-updates/main amd64 nfs-common amd64 1:2.6.1-1ubuntu1.2 [241 kB]
Fetched 330 kB in 0s (1,110 kB/s)
Selecting previously unselected package libnfsidmap1:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 80125 files and directories currently installed.)
Preparing to unpack .../libnfsidmap1_1%3a2.6.1-1ubuntu1.2_amd64.deb ...
Unpacking libnfsidmap1:amd64 (1:2.6.1-1ubuntu1.2) ...
Selecting previously unselected package rpcbind.
Preparing to unpack .../rpcbind_1.2.6-2build1_amd64.deb ...
Unpacking rpcbind (1.2.6-2build1) ...
Selecting previously unselected package nfs-common.
Preparing to unpack .../nfs-common_1%3a2.6.1-1ubuntu1.2_amd64.deb ...
Unpacking nfs-common (1:2.6.1-1ubuntu1.2) ...
Setting up libnfsidmap1:amd64 (1:2.6.1-1ubuntu1.2) ...
Setting up rpcbind (1.2.6-2build1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/rpcbind.service → /lib/systemd/system/rpcbind.service.
Created symlink /etc/systemd/system/sockets.target.wants/rpcbind.socket → /lib/systemd/system/rpcbind.socket.
Setting up nfs-common (1:2.6.1-1ubuntu1.2) ...

Creating config file /etc/idmapd.conf with new version

Creating config file /etc/nfs.conf with new version
Adding system user `statd' (UID 116) ...
Adding new user `statd' (UID 116) with group `nogroup' ...
Not creating home directory `/var/lib/nfs'.
Created symlink /etc/systemd/system/multi-user.target.wants/nfs-client.target → /lib/systemd/system/nfs-client.target.
Created symlink /etc/systemd/system/remote-fs.target.wants/nfs-client.target → /lib/systemd/system/nfs-client.target.
auth-rpcgss-module.service is a disabled or a static unit, not starting it.
nfs-idmapd.service is a disabled or a static unit, not starting it.
nfs-utils.service is a disabled or a static unit, not starting it.
proc-fs-nfsd.mount is a disabled or a static unit, not starting it.
rpc-gssd.service is a disabled or a static unit, not starting it.
rpc-statd-notify.service is a disabled or a static unit, not starting it.
rpc-statd.service is a disabled or a static unit, not starting it.
rpc-svcgssd.service is a disabled or a static unit, not starting it.
rpc_pipefs.target is a disabled or a static unit, not starting it.
var-lib-nfs-rpc_pipefs.mount is a disabled or a static unit, not starting it.
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
+ apt-get install -y apt-transport-https ca-certificates
Reading package lists...
Building dependency tree...
Reading state information...
ca-certificates is already the newest version (20230311ubuntu0.22.04.1).
ca-certificates set to manually installed.
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 11 not upgraded.
Need to get 1,510 B of archives.
After this operation, 169 kB of additional disk space will be used.
Get:1 http://ca.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 apt-transport-https all 2.4.10 [1,510 B]
Fetched 1,510 B in 0s (4,051 B/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 80238 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_2.4.10_all.deb ...
Unpacking apt-transport-https (2.4.10) ...
Setting up apt-transport-https (2.4.10) ...
+ command -v setcap
/usr/sbin/setcap
+ command -v node
/snap/bin/node
+ command -v npm
/snap/bin/npm
+ node -v 2>/dev/null| grep -Eo '[0-9.]+' | cut -d'.' -f1
18
+ command -v yarn
/snap/bin/yarn
+ /bin/systemctl enable redis-server && /bin/systemctl start redis-server
Synchronizing state of redis-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable redis-server
+ /bin/systemctl enable rpcbind && /bin/systemctl start rpcbind
Synchronizing state of rpcbind.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable rpcbind
+ mkdir -p "/opt/xo"
+ mkdir "/opt/xo/xo-builds"
+ mkdir -p "/opt/xo/xo-src/xen-orchestra"
+ git clone "https://github.com/vatesfr/xen-orchestra" "/opt/xo/xo-src/xen-orchestra"
Cloning into '/opt/xo/xo-src/xen-orchestra'...
+ rm -rf "/opt/xo/xo-builds/xen-orchestra-202308252321"
+ cp -r "/opt/xo/xo-src/xen-orchestra" "/opt/xo/xo-builds/xen-orchestra-202308252321"
+ cd /opt/xo/xo-builds/xen-orchestra-202308252321 && git rev-parse HEAD
3baa37846e6dbe775a8891f51f7eaebbbb28bea6
+ cd /opt/xo/xo-builds/xen-orchestra-202308252321 && git rev-parse --short HEAD
3baa37846
+ cd .
Installing Xen Orchestra from branch: master - commit: 3baa37846
+ cd /opt/xo/xo-builds/xen-orchestra-202308252321 && yarn && yarn build
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning url-loader@1.1.2: Invalid bin field for "url-loader".
[4/5] Linking dependencies...
warning "workspace-aggregator-3084da3f-b992-4958-8ef2-370adec24ca1 > @vates/node-vsphere-soap > soap@1.0.0" has incorrect peer dependency "axios@^0.27.2".
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 153.60s.
yarn run v1.22.19
$ turbo run build --scope xo-server --scope xo-server-'*' --scope xo-web
• Packages in scope: xo-server, xo-server-audit, xo-server-auth-github, xo-server-auth-google, xo-server-auth-ldap, xo-server-auth-oidc, xo-server-auth-saml, xo-server-backup-reports, xo-server-load-balancer, xo-server-netbox, xo-server-perf-alert, xo-server-sdn-controller, xo-server-test, xo-server-test-plugin, xo-server-transport-email, xo-server-transport-icinga2, xo-server-transport-nagios, xo-server-transport-slack, xo-server-transport-xmpp, xo-server-usage-report, xo-server-web-hooks, xo-web
• Running build in 22 packages
• Remote caching disabled

 Tasks:    26 successful, 26 total
Cached:    0 cached, 26 total
  Time:    2m53.407s 

Done in 174.36s.
+ find "/opt/xo/xo-builds/xen-orchestra-202308252321/packages/" -maxdepth 1 -mindepth 1 -not -name "xo-server" -not -name "xo-web" -not -name "xo-server-cloud" -not -name "xo-server-test*" -exec ln -sn {} "/opt/xo/xo-builds/xen-orchestra-202308252321/packages/xo-server/node_modules/" \;
+ pgrep -f xo-server
+ sed -i "s#ExecStart=.*#ExecStart=/opt/xo\/xo-server\/dist\/cli.mjs#" /opt/xo/xo-builds/xen-orchestra-202308252321/packages/xo-server/xo-server.service
+ sed -i "/ExecStart=.*/a WorkingDirectory=/opt/xo/xo-server" /opt/xo/xo-builds/xen-orchestra-202308252321/packages/xo-server/xo-server.service
+ find /etc/systemd/system -maxdepth 1 -type l -name 'xo-server.service'
+ /bin/cp -f /opt/xo/xo-builds/xen-orchestra-202308252321/packages/xo-server/xo-server.service /etc/systemd/system/xo-server.service
+ /bin/systemctl daemon-reload
+ sed -i "s%#'/any/url' = '/path/to/directory'%'/' = '/opt/xo/xo-web/dist/'%" /opt/xo/xo-builds/xen-orchestra-202308252321/packages/xo-server/sample.config.toml
+ sed -i "s%#uri = 'redis://redis.company.lan/42'%uri = 'redis://127.0.0.1:6379/0'%" /opt/xo/xo-builds/xen-orchestra-202308252321/packages/xo-server/sample.config.toml
+ mkdir -p /root/.config/xo-server
+ mv -f /opt/xo/xo-builds/xen-orchestra-202308252321/packages/xo-server/sample.config.toml /root/.config/xo-server/config.toml
+ ln -sfn /opt/xo/xo-builds/xen-orchestra-202308252321/packages/xo-server /opt/xo/xo-server
+ ln -sfn /opt/xo/xo-builds/xen-orchestra-202308252321/packages/xo-web /opt/xo/xo-web
+ ln -sfn /opt/xo/xo-builds/xen-orchestra-202308252321/packages/xo-cli /opt/xo/xo-cli
+ ln -sfn /opt/xo/xo-cli/index.mjs /usr/local/bin/xo-cli
+ /bin/systemctl start xo-server
+ journalctl --since '2023-08-25 23:21:19' -u xo-server | grep 'Web server listening on https\{0,1\}:\/\/.*:80'
+ journalctl --since '2023-08-25 23:21:19' -u xo-server | grep 'Web server listening on https\{0,1\}:\/\/.*:80'
+ journalctl --since '2023-08-25 23:21:19' -u xo-server | grep 'Web server listening on https\{0,1\}:\/\/.*:80'
+ journalctl --since '2023-08-25 23:21:19' -u xo-server | grep 'Web server listening on https\{0,1\}:\/\/.*:80'
+ journalctl --since '2023-08-25 23:21:19' -u xo-server | grep 'Web server listening on https\{0,1\}:\/\/.*:80'
+ journalctl --since '2023-08-25 23:21:19' -u xo-server | grep 'Web server listening on https\{0,1\}:\/\/.*:80'
+ journalctl --since '2023-08-25 23:21:19' -u xo-server | grep 'Web server listening on https\{0,1\}:\/\/.*:80'

Installation failed
xo-server service log:

+ journalctl --since '2023-08-25 23:21:19' -u xo-server >> /home/sam/XenOrchestraInstallerUpdater/logs/xo-install.log-202308252321
Aug 25 23:27:39 athena systemd[1]: Started XO Server.
Aug 25 23:27:43 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:27:43 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:27:43 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 1.
Aug 25 23:27:43 athena systemd[1]: Stopped XO Server.
Aug 25 23:27:43 athena systemd[1]: Started XO Server.
Aug 25 23:27:46 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:27:46 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:27:46 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 2.
Aug 25 23:27:46 athena systemd[1]: Stopped XO Server.
Aug 25 23:27:46 athena systemd[1]: Started XO Server.
Aug 25 23:27:48 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:27:48 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:27:48 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 3.
Aug 25 23:27:48 athena systemd[1]: Stopped XO Server.
Aug 25 23:27:48 athena systemd[1]: Started XO Server.
Aug 25 23:27:51 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:27:51 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:27:51 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 4.
Aug 25 23:27:51 athena systemd[1]: Stopped XO Server.
Aug 25 23:27:51 athena systemd[1]: Started XO Server.
Aug 25 23:27:54 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:27:54 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:27:54 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Aug 25 23:27:54 athena systemd[1]: Stopped XO Server.
Aug 25 23:27:54 athena systemd[1]: Started XO Server.
Aug 25 23:27:57 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:27:57 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:27:57 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 6.
Aug 25 23:27:57 athena systemd[1]: Stopped XO Server.
Aug 25 23:27:57 athena systemd[1]: Started XO Server.
Aug 25 23:28:00 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:28:00 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:28:00 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 7.
Aug 25 23:28:00 athena systemd[1]: Stopped XO Server.
Aug 25 23:28:00 athena systemd[1]: Started XO Server.
Aug 25 23:28:03 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:28:03 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:28:03 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 8.
Aug 25 23:28:03 athena systemd[1]: Stopped XO Server.
Aug 25 23:28:03 athena systemd[1]: Started XO Server.
Aug 25 23:28:06 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:28:06 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:28:06 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 9.
Aug 25 23:28:06 athena systemd[1]: Stopped XO Server.
Aug 25 23:28:06 athena systemd[1]: Started XO Server.
Aug 25 23:28:09 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:28:09 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:28:09 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 10.
Aug 25 23:28:09 athena systemd[1]: Stopped XO Server.
Aug 25 23:28:09 athena systemd[1]: Started XO Server.
Aug 25 23:28:12 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:28:12 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:28:12 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 11.
Aug 25 23:28:12 athena systemd[1]: Stopped XO Server.
Aug 25 23:28:12 athena systemd[1]: Started XO Server.
Aug 25 23:28:15 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:28:15 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:28:15 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 12.
Aug 25 23:28:15 athena systemd[1]: Stopped XO Server.
Aug 25 23:28:15 athena systemd[1]: Started XO Server.
Aug 25 23:28:18 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:28:18 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:28:18 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 13.
Aug 25 23:28:18 athena systemd[1]: Stopped XO Server.
Aug 25 23:28:18 athena systemd[1]: Started XO Server.
Aug 25 23:28:20 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:28:20 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:28:21 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 14.
Aug 25 23:28:21 athena systemd[1]: Stopped XO Server.
Aug 25 23:28:21 athena systemd[1]: Started XO Server.
Aug 25 23:28:23 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:28:23 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:28:24 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 15.
Aug 25 23:28:24 athena systemd[1]: Stopped XO Server.
Aug 25 23:28:24 athena systemd[1]: Started XO Server.
Aug 25 23:28:26 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:28:26 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:28:27 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 16.
Aug 25 23:28:27 athena systemd[1]: Stopped XO Server.
Aug 25 23:28:27 athena systemd[1]: Started XO Server.
Aug 25 23:28:29 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:28:29 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:28:30 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 17.
Aug 25 23:28:30 athena systemd[1]: Stopped XO Server.
Aug 25 23:28:30 athena systemd[1]: Started XO Server.
Aug 25 23:28:32 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:28:32 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:28:33 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 18.
Aug 25 23:28:33 athena systemd[1]: Stopped XO Server.
Aug 25 23:28:33 athena systemd[1]: Started XO Server.
Aug 25 23:28:35 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:28:35 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:28:35 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 19.
Aug 25 23:28:35 athena systemd[1]: Stopped XO Server.
Aug 25 23:28:35 athena systemd[1]: Started XO Server.
Aug 25 23:28:38 athena systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 25 23:28:38 athena systemd[1]: xo-server.service: Failed with result 'exit-code'.
Aug 25 23:28:38 athena systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 20.
Aug 25 23:28:38 athena systemd[1]: Stopped XO Server.
Aug 25 23:28:38 athena systemd[1]: Started XO Server.
`

**Comment by swtrse** [comment]
I did run into the same error, so it seams to be back. Running the install script on Debian 12 and RockyLinux 9
On both system I used a user with sudo rights to run the script with `sudo ./xo-install.sh'.
The config I used in both OSes is
```
# Optional user that runs the service
# default: root
# no effect to Xen Orchestra proxy
XOUSER="xoa"

# Optional parameter if running as non privileged user to use sudo when mounting/umounting shares inside Xen Orchest>
# no effect if XOUSER is root
# options true/false
# no effect to Xen Orchestra proxy
USESUDO=true

# Optional parameter to generate sudoers config when missing completely if USESUDO is set to true
# no effect if XOUSER is root
# options true/false
# no effect to Xen Orchestra proxy
GENSUDO=true

# Port number where xen-orchestra service is bound
# no effect to Xen Orchestra proxy
PORT="443"

# Base dir for installation and future updates
INSTALLDIR="/opt/xo"

# Script will update itself if there's a newer version available. This assumes that script inside a git directory an>
# options: true/false
SELFUPGRADE=true

# Xen Orchestra configuration file is stored in XOUSER's home directory ($HOME/.config/xo-server/config.toml) and by>
# You may disable this if you edit configuration by hand and don't want an update to overwrite it. Note that some of>
# options: true/false
# no effect to Xen Orchestra proxy
CONFIGUPDATE=true

# Location of Xen Orchestra repository where source code is fetched
REPOSITORY="https://github.com/vatesfr/xen-orchestra"

# Git branch, tag (append tags/ before the tag name) or individual commit where xen-orchestra sources are fetched.
BRANCH="master"

# Installation log path
# default: ./logs
#LOGPATH=

# Only one PLUGINS variable can be used at a time. Comment out the other one if you change these below. Comment out >

# Comma separated list of plugins to be installed, check README for more information. Note that 3rd party plugins de>
#PLUGINS="xo-server-transport-email,xo-server-usage-report,xo-server-perf-alert"

# (default) all plugins will be installed, including possible 3rd-party plugins if defined.
PLUGINS="all"

# Additional 3rd-party plugins to fetch. Keep the .git suffix.
#ADDITIONAL_PLUGINS="https://github.com/user/repo.git,https://github.com/user/repo2.git"

# NodeJS and Yarn are automatically updated when running update/install. Can be disabled but not recommended (instal>
# Note that if nodejs is updated when script's update feature is used, it might not be possible to use rollback opti>
# options: true/false
AUTOUPDATE=true

# yarn cache can consume a lot of disk space over time. Setting this to true will clear cache after update.
# this can have a negative impact on how long update will take with slower internet connections
# options: true/false
#YARN_CACHE_CLEANUP="false"

# enable/disable OS check. Installation refuses to run on any other than supported OS versions if this is enabled. C>
# options: true/false
OS_CHECK=true

# enable/disable architecture check. Installation refuses to run on any other than x86_64 if enabled. Can be disable>
# options: true/false
ARCH_CHECK=true

# Define the number of previous successful installations you want to keep. Needs to be at least 1. Determines how fa>
PRESERVE="3"

# certificate settings have no effect to Xen Orchestra proxy, it'll generate it's own self-signed certificates always

# Location of pem certificate/key files. Installation will automatically configure HTTPS if these are defined. Remem>
PATH_TO_HTTPS_CERT=$INSTALLDIR/xo.crt
PATH_TO_HTTPS_KEY=$INSTALLDIR/xo.key

# location of CA certificate file.
# define this if your host certificate is issued by a custom CA and you want XO to trust it.
# file can contain multiple certificates
#PATH_TO_HOST_CA=

# If set to true together with cert/key paths, defined pem key/certificate will be created if neither exists.
# options: true/false
AUTOCERT=true

# Enable automatic ACME (eq. Let's Encrypt) certificate creation.
# Setting this to true will configure HTTP and HTTPS listeners to ports 80/443 (overwrites PORT variable),
# enables autocert, sets certificate paths if missing and adds http to https redirect.
#ACME="false"

# ACME domain for which the certificate is generated.
# Domain needs to be pointed towards XO server public ip-address and ports 80 and 443 allowed.
#ACME_DOMAIN=""

# Optional email address to receive notifications related to certificate
#ACME_EMAIL=""

# Optional ACME CA to use. Will default to Let's Encrypt
# Available ones listed here: https://www.npmjs.com/package/acme-client#directory-urls
#ACME_CA="letsencrypt/production"

# If set to true, this will install the rpm/deb repositories necessary for the Xen Orchestra install.
# If set to false, these repositories will not be installed. Also automatic nodejs upgrade will be disabled.
# Note that installation will fail if all needed packages aren't available from configured repositories. See README >
# options: true/false
# default: true
#INSTALL_REPOS="true"

# Send xo-server logs to remote syslog
# syntax is: <protocol>://<target-address>:<port>
# supported protocols are udp and tcp
# example: tcp://syslog.company.lan:514
#SYSLOG_TARGET=""
```

**Comment by ronivay** [comment]
This is a very generic error and there can be multiple reasons for it. Original issue here shouldn't be related at all. Please open up a new issue with logs attached for further investigation.
