### ISSUE TITLE
Query on the identifying the host for running this script to access the fresh installed xcp-ng PC.

### ISSUE THREAD

**Issue by abykal** [ronivay/XenOrchestraInstallerUpdater#225]
**Query**
Where this script needs to executed? I am asking about the host system where this needs to be run.

There is two installation methods you listed here and either one you can choose for this purpose. 
1. Via Script on a already up VM  
2. Generates a VM along with script.
As, xcp-ng is already installed on a system. 

1. Is both methods (either of one) to be run on same xcp-ng host at command line?
      If I run image option#2 directly in xcp-ng host, will this method generate a vm with xo, to be hosted and linked under xcp-ng
      hypervisor?
2. Or in a different system?
    Eg: like, script method#1 in a fresh linux VM hosted inside hyperV in Windows PC OR directly in a linux PC terminal.

It would be really helpful to get a clarity on the environment of xo deployment.

**Comment by ronivay** [comment]
Hey,

XCP-ng host (the mgmt VM aka dom0) is something you shouldn't install any additional software to, `xo-install.sh` has a safeguard for this and will bail out if you attempt it :) That's why there's the `xo-vm-import.sh` which you need to run specifically on an XCP-ng dom0 and it isn't installing anything to the host, but just importing a VM that runs inside your XCP-ng pool. 

Xen Orchestra and `xo-install.sh` itself can run anywhere on a supported OS, whether it's a VM inside your XCP-ng pool which you are managing with it, or in a separate environment like HyperV etc, it can even be installed on a separate physical server if you wish. This is completely up to you where you want to put it.

I've tried to be clear with this in the README but i'm open for ideas if you think this should be clarified somehow.

**Comment by dsiminiuk** [comment]
There are so many ways to do this. I've had a Ubuntu VM inside TrueNAS running Xen Orchestra, and at the moment I am running it on a Ubuntu VM in VMware Workstation running on a Linux Mint Desktop.
