### ISSUE TITLE
Why not have new packages enabled as part of the update call?

### ISSUE THREAD

**Issue by patelnet** [ronivay/XenOrchestraInstallerUpdater#39]
Not really an issue but a feature enhancement.  Why would you not want to add the option to install new packages as part of the update?  It seems that would be a helpful thing to do.

**Comment by ronivay** [comment]
Hello,

Thanks for a suggestion. I assume you mean updating the existing packages during XO update?

Goal is to make as little changes to the underlying operating system as possible. This gives the user a freedom to do system updates as they wish. Update option also serves as a way to install XO and let the user install dependencies themselves should they want to.

I kinda expect users to keep their servers up-to-date and not trust a separate script for this (unless explicitly meant for the purpose) and therefore don't see the point of having such option. This script isn't trying to implement sort of XO appliance after all.

Different story if some of the dependencies being outdated for some reason breaks the update procedure, but so far seen only older yarn being an issue and that's why yarn/nodejs update is currently optional during update option.

**Comment by ronivay** [comment]
Please reopen if my explanation didn't make sense or there's more to it. 

As said, this is by design and until someone convinces me why this doesn't work, it'll stay as it is :)
