### ISSUE TITLE
Netdata / Advanced Live Telementary

### ISSUE THREAD

**Issue by andyjhall** [ronivay/XenOrchestraInstallerUpdater#40]
Any plans to add this? looks like if you pay for an xoa premium license you get it.

If so im happy to start work on a pull request. 

Additional info here:
https://xcp-ng.org/forum/topic/2288/netdata-package-is-now-available-in-xcp-ng
https://xcp-ng.org/forum/topic/2859/netdata-plugin-open-or-closed-source/10?lang=en-US

On the face of it, looks like we would need to install netdata on the host and create a reverse proxy for it.

**Comment by ronivay** [comment]
Hi,

Haven't played around with this. Doesn't seem to be implemented as a plugin, so it's builtin. XOA does the package installation on the host and enables a reverse proxy between user and host. 

If it's meant to be only a part of XOA, then i'm probably not interested in trying to hack a way into adding it. But need to look into it a bit.

**Comment by ronivay** [comment]
Okay tested the functionality shortly. Indeed it seems that the "Enable Advanced Live Telemetry" button doesn't change to anything even though netdata-ui package is installed on the host. I kinda hoped that it would change to URL and then this would've been doable. 

Since it can't be integrated as a part of xen orchestra in way that it's just a clickable button in the UI (without modifying sources) i think we need to pass this. It's almost as easy to just access http://host-ip:19999 or instruct users to open something like http://xo-ip/host-ip which then reverse proxies things to that said host. This would also require explaining how to correctly firewall the netdata port to xen orchestra only and so on.

If you know more about this or already had some implementation idea, i'd be happy to hear any suggestions.

**Comment by ronivay** [comment]
I’ll close this because there’s really no easy way to implement this. We can’t use the functionality built into XOA and therefore the outcome at it’s best would still be kind of a hack and would require constant maintenance.

**Comment by Tommy0046** [comment]
Hi, 

I was able to get netdata plugin showed up using this: https://github.com/pratheekrebala/xo-server-netdata
It is an old version v0.1.0 vs current v0.2.0 in XOA. However I wasnt able to get it to work, so I registered for XOA premium trial, and will try to see how it is configured, so maybe I can find something...
