### ISSUE TITLE
Update documentation on how to do SSL install?

### ISSUE THREAD

**Issue by DPerkunas** [ronivay/XenOrchestraInstallerUpdater#61]
Thank you for the script, can you update the documentation to show how to enable port 443 and self signed cert during install?

I've tried editing the /etc/xo/xo-server/config and install cfg's with no luck.

**Comment by ronivay** [comment]
Hi,

Documentation tells you to edit the configuration (xo-install.cfg) according to your preference. Change port from 80 to 443 and add paths to your certificate/key files and installation will configure xen orchestra for you.

**Comment by curvingedge** [comment]
I'm not sure If I can add a question to this. After configuring the cfg file and adding the cert files to the directories, what is the least destructive way to install the certs? ./xo-install.sh --update? Is this the best way for an existing install and also for updating certs when they expire?

**Comment by curvingedge** [comment]
> I'm not sure If I can add a question to this. After configuring the cfg file and adding the cert files to the directories, what is the least destructive way to install the certs? ./xo-install.sh --update? Is this the best way for an existing install and also for updating certs when they expire?

I've tried the update command and it didn't add the ssl certs. Would I need to install? If I do will it overwrite my current install?

**Comment by ronivay** [comment]
Hi,

Update will also update configuration This requires that there is something to update, if latest master branch version matches currently installed version, nothing is done. This should be clear from the script output when you attempt to run it.

When you run xo-install.sh, it'll tell you the location of xen orchestra configuration file, which by default is $HOME/.config/xo-server/config.toml. You can edit port/certificate details to this configuration file as well if you wish. Just remember to either switch off configuration file update from xo-install.cfg (CONFIGUPDATE variable) or add those port/cert path changes to xo-install.cfg so that next time you run update, it'll add that HTTPS stuff to your xen orchestra config.

**Comment by curvingedge** [comment]
Thanks, I got it working now.
