### ISSUE TITLE
Applicance file not there

### ISSUE THREAD

**Issue by seanlinder** [ronivay/XenOrchestraInstallerUpdater#63]
When attempting to deploy the appliance I am finding that the image.xva is not complete. It downloads an image.xva file that is 0M.

**Comment by JPOLDGIT** [comment]
I am having the exact same issue no image.xva is available.  This has been the case since last friday.

**Comment by ronivay** [comment]
Hi,

Thank you. I made some changes to the platform where image is built. This caused some unexpected behaviour which caused an empty image to be uploaded. Made some adjustments so that this won't happen again. There's now an image in place, fresh out from the oven.

Empty image was uploaded yesterday around 03:00 UTC. @JPOLDGIT if this really has been not working for you since friday, then it's something else and i'll need some more information to debug.
