### ISSUE TITLE
Rasberry Pie 4/ 4gb Error, Worked before

### ISSUE THREAD

**Issue by MrWaste** [ronivay/XenOrchestraInstallerUpdater#65]
**OS Version**:
**Node.js version**: node -v
**Yarn version**: yarn -v

**Server specs**
Rasberry Pie 4

**Issue**
Xen Orchestra was about 1 month outdated and seems they have remove the option of using the pi. Before this update the pi it would work like any other computer that isn't arm. Everything work and I mean everything.

I ran the update and it broke itself. I wiped it put a new pi os (Clean). Now is giving me an error.
It worked before why can't I use it now?

**Installation logfile**
```
Installation only supports 64bit OS. You seem to be running architecture: armv71
```

**Comment by MrWaste** [comment]
Thanks, I found this in there. Now I have waste more time removing this..

function CheckOS {

	if [[ $(uname -m) != "x86_64" ]]; then
		printfail "Installation only supports 64bit OS. You seem to be running architecture: $(uname -m)"
		exit 1
	fi

	if [ -f /etc/centos-release ] ; then
		OSVERSION=$(grep -Eo "[0-9]" /etc/centos-release | head -1)
		OSNAME="CentOS"
		if [[ $OSVERSION != "8" ]]; then
			printfail "Only CentOS 8 supported"
			exit 1
		fi
		cmdlog "which xe"
		if [[ $(which xe 2>>$LOGFILE) ]]; then
			printfail "xe binary found, don't try to run install on xcp-ng/xenserver host. use xo-appliance.sh instead"
			exit 1
		fi
	elif [[ -f /etc/os-release ]]; then
		OSVERSION=$(grep ^VERSION_ID /etc/os-release | cut -d'=' -f2 | grep -Eo "[0-9]{1,2}" | head -1)
		OSNAME=$(grep ^NAME /etc/os-release | cut -d'=' -f2 | sed 's/"//g' | awk '{print $1}')
		if [[ $OSNAME == "Debian" ]] && [[ ! $OSVERSION =~ ^(8|9|10)$ ]]; then
			printfail "Only Debian 8/9/10 supported"
			exit 1
		elif [[ $OSNAME == "Ubuntu" ]] && [[ ! $OSVERSION =~ ^(16|18|20)$ ]]; then
			printfail "Only Ubuntu 16/18/20 supported"
			exit 1
		fi
	else
		printfail "Only CentOS 8 / Ubuntu 16/18 and Debian 8/9 supported"
		exit 1
	fi

}

**Comment by MrWaste** [comment]
I removed this code below. Error /opt/xo/xo-builds/xen-orchestraInstallerUpdater/logs/xo-install.log- (random numbers)
Says "failed to installation."

Could you please fix this soon, I really need XenOrchestra online then I can access machines.


if [[ $(uname -m) != "x86_64" ]]; then
	printfail "Installation only supports 64bit OS. You seem to be running architecture: $(uname -m)"
	exit 1
fi

**Comment by ronivay** [comment]
Hi,

I Raspbian listen as a supported OS? No it is not. Yes it might've been working earlier since it identifies itself essentially as Debian.

I get your frustration but you've ran unsupported configuration from the beginning. What this script does is essentially the manual installation procedure described in Xen Orchestra's own documentation where certain dependencies come from and 64bit OS is one of them. This wasn't checked by this script earlier so installation was ran on 32bit/arm architectures as well. There is no quarantees that some package dependencies and their versions are correct for arm as it happened with 32bit already.

You're free to make a patch for yourself if you wish to continue running on RaspberryPi, but it won't be added here simply because it isn't supported by Xen Orchestra itself.

**Comment by MrWaste** [comment]
@ronivay 
The rassberry Pi has a 64 bit os now, in beta. I have installed it however, it is aarch64. Can you add aarch64 to the what if statement to allow only aarch64?


64 Bit Os
https://www.raspberrypi.org/forums/viewtopic.php?t=275370

**Comment by ronivay** [comment]
It is Xen Orchestra itself which dictates the requirements, this script only follows the documented procedure as i said. You can even skip using this script completely and just follow the official procedure yourself https://xen-orchestra.com/docs/from_the_sources.html. Just deal with all the package/dependency requirements yourself.

**Comment by MrWaste** [comment]
Could you at least add it as a maybe for testing only? If anything breaks it is on you.

**Comment by MrWaste** [comment]
If I would go out to the store and get a x86/64 bit like this, will this work?

https://liliputing.com/2020/10/the-59-rock-pi-x-is-like-a-windows-compatible-raspberry-pi-with-an-x86-processor.html

**Comment by ronivay** [comment]
Please, try to understand. You have all the tools you need to do testing as much as you wish. Edit my script or skip to official procedure completely if this doesn't work for your specific use case. No, i won't be adding any experimental architectures or OS's which i can't test properly and/or aren't supported officially.

I have no experience of that hardware you linked. Most likely since it's x86 it works just fine.

**Comment by ronivay** [comment]
Hello,

I remembered you requested this earlier. Latest version of script now supports the possibility to disable OS/Architecture checks if one wants to experiment. There is still no quarantee that installation works, actually it most likely fails when checks are disabled but option is there anyway :)
