### ISSUE TITLE
Alma Linux or Rocky Linux support

### ISSUE THREAD

**Issue by bberndt** [ronivay/XenOrchestraInstallerUpdater#74]
Are there plans to support Rocky Linux, and or Alma Linux?

**Comment by ronivay** [comment]
Not yet, but since CentOS is going to be EOL, i will probably start supporting Alma Linux. Most likely i won't add many RHEL based distros as supported, but i've already had some plans to give option to remove OS/arch checks. This would give the option to run on any deb/rpm based derivatives which might or might not work but wouldn't stop to OS not being supported.

I will keep this open as a reminder :)

**Comment by ronivay** [comment]
There's now support (somewhat in beta still) for AlmaLinux. I also implemented the option to disable OS check so in theory any RHEL 8 based distro should work. Obviously using this option won't have any further support if it fails.

**Comment by bberndt** [comment]
Cool, Thanks!
